#!/usr/bin/env bash
# configures an Ubuntu server with localhost resolves to
# 127.0.0.2 and facebook.com resolves to 8.8.8.8
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
cp /etc/hosts /etc/hosts.bak
sed -i '/127.0.0.1\s\+localhost/s/127.0.0.1/127.0.0.2/' /etc/hosts
if grep -q "facebook.com" /etc/hosts; then
    sed -i '/facebook.com/s/.*/8.8.8.8 facebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
